### ISSUE TITLE
看源码时有一个疑问

### ISSUE THREAD

**Issue by kaixinbaba** [yizt/keras-ctpn#23]
```python
def smooth_l1_loss(y_true, y_predict, sigma2=9.0):
    abs_diff = tf.abs(y_true - y_predict, name='abs_diff')
    loss = tf.where(tf.less(abs_diff, 1. / sigma2), 0.5 * sigma2 * tf.pow(abs_diff, 2), abs_diff - 0.5 / sigma2)
    return loss
```
在源码中有一个关于smooth l1的loss的函数，我网上查询到的smooth l1的定义是
![image](https://user-images.githubusercontent.com/22809336/76503042-0f175400-6480-11ea-875c-a17d050d16ee.png)
当函数sigma2=1的时候和网上定义的是一致的，
但是我看大佬这里用的是9.0的默认值，说实话以我的水平第一眼觉得是不是应该是0.9？
想请问大佬这里sigma2的默认值为什么要设置成9.0，有什么用意或者是经过测试这个数字比较好吗

**Comment by yizt** [comment]
@kaixinbaba 这个sigma2=9.0是借鉴的其他人的，没有做实验；

**Comment by kaixinbaba** [comment]
好的 谢谢
