### ISSUE TITLE
text_proposals.py文件apply_regress函数的侧边精调代码是不是有问题？第38行

### ISSUE THREAD

**Issue by chenying99** [yizt/keras-ctpn#29]
text_proposals.py文件apply_regress函数第38行代码
cx += dx * w

而target.py文件中side_regress_target函数中代码（第83行），dx计算方式为：
dx = (gt_center_x - center_x) * 2 / w

貌似 不能这么计算吧？  cx += dx * w

后面有cx + w * 0.5， cx - w * 0.5 ；  
这里w是anchor_box的width，也不是预测box的width，是不是有问题？

**Comment by yizt** [comment]
@chenying99 感谢您的反馈，这里应该是没有问题的，a) 侧边的偏移相当于中心点偏移的两倍，所以计算偏移的时候*2，但是应用的侧边偏移的时候，不是要把中心点重合，二是侧边要重合；b)  w本来就是anchor_box的width

**Comment by chenying99** [comment]
谢谢，好像没问题，最后得出的坐标是基于anchor_box的左右坐标，然后加上偏移（dx * w）
