### ISSUE TITLE
正负样本编号问题

### ISSUE THREAD

**Issue by RabbearSu** [yizt/keras-ctpn#4]
https://github.com/yizt/keras-ctpn/blob/9427448873ec187eb35379ce382a5529ecc5d84f/ctpn/layers/target.py#L161
为什么正样本要在原始的anchor_indices中(tf.gather)，而negative的indices不需要变换？

**Comment by yizt** [comment]
@RabbearSu 非常感谢您的反馈，这是一个bug,已经修复；
