### ISSUE TITLE
标志位问题

### ISSUE THREAD

**Issue by RabbearSu** [yizt/keras-ctpn#5]
https://github.com/yizt/keras-ctpn/blob/6b962f833bc3abc6e2b19aafa288738130c6b735/ctpn/layers/losses.py#L17

true_cls_ids和indices的标志位说明是否错误？在target.py文件中，cls_ids的正负样本tag均为1，而padding样本为0；indices的tag生成为，正样本为1，负样本为-1，padding样本为0。
请查看，谢谢！

**Comment by yizt** [comment]
@RabbearSu 感谢您的反馈，备注有些地方是有不一致的地方，主要原因是，代码的逻辑改了，备注可能没有相应的修改。

**Comment by RabbearSu** [comment]
> @RabbearSu 感谢您的反馈，备注有些地方是有不一致的地方，主要原因是，代码的逻辑改了，备注可能没有相应的修改。

原来如此，了解了
