### ISSUE TITLE
deltas维度错误

### ISSUE THREAD

**Issue by RabbearSu** [yizt/keras-ctpn#6]
https://github.com/yizt/keras-ctpn/blob/6b962f833bc3abc6e2b19aafa288738130c6b735/ctpn/layers/losses.py#L68

应为 `deltas = tf.gather_nd(deltas[..., :-1], positive_indices) `，deltas为3维

**Comment by yizt** [comment]
@RabbearSu 感谢您的反馈！这里只做垂直方向的中心点偏移和高度回归，所以取:-2取到(dy,dh)没有错。

**Comment by RabbearSu** [comment]
> @RabbearSu 感谢您的反馈！这里只做垂直方向的中心点偏移和高度回归，所以取:-2取到(dy,dh)没有错。

好的，我又看了一下，您说的没错，谢谢~
