### ISSUE TITLE
请问image_annotation怎么制作，格式如何

### ISSUE THREAD

**Issue by RabbearSu** [yizt/keras-ctpn#7]
请问您的image_annotation是什么格式的呢，怎么制作的呢？
thanks!

**Comment by yizt** [comment]
@RabbearSu 您好！image_annotation是字典，'image_path','quadrilaterals','labels'这三个key是必须的。
image_path:图像路径
quadrilaterals: 二维numpy数组，标注区域四边形坐标[n,(lt_x, lt_y, rt_x, rt_y, rb_x, rb_y, lb_x, lb_y)]
labels:一维numpy数组[n]，值都是1;  （n:是标注个数)

**Comment by RabbearSu** [comment]
@yizt 谢谢哥们儿！
